### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by arthur1976** [ModuleArt/qpv-plugins#1]
这些插件怎么下载安装啊？安装在哪里？

**Comment by Beelink** [comment]
These plugins still in active development and few of them will be available in the next release of the Quick Picture Viewer. Just wait for an update. If you have any proposition regarding the new plugins you can request one here.

**Comment by arthur1976** [comment]
好的 期待中




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ModuleArt/qpv-plugins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ModuleArt/qpv-plugins] 求助 (#1)





 
These plugins still in active development and few of them will be available in the next release of the Quick Picture Viewer. Just wait for an update. If you have any proposition regarding the new plugins you can request one here.
